language: go
go:
 - "1.25.x"

env:
  - GO111MODULE=on

install: true

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s v2.5.0

script:
  - golangci-lint run
  - go test -v ./collector
